package mediformapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SavedFormsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSavedFormsAllPropertiesEquals(SavedForms expected, SavedForms actual) {
        assertSavedFormsAutoGeneratedPropertiesEquals(expected, actual);
        assertSavedFormsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSavedFormsAllUpdatablePropertiesEquals(SavedForms expected, SavedForms actual) {
        assertSavedFormsUpdatableFieldsEquals(expected, actual);
        assertSavedFormsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSavedFormsAutoGeneratedPropertiesEquals(SavedForms expected, SavedForms actual) {
        assertThat(expected)
            .as("Verify SavedForms auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSavedFormsUpdatableFieldsEquals(SavedForms expected, SavedForms actual) {
        assertThat(expected)
            .as("Verify SavedForms relevant properties")
            .satisfies(e -> assertThat(e.getSavedFormID()).as("check savedFormID").isEqualTo(actual.getSavedFormID()))
            .satisfies(e -> assertThat(e.getFormID()).as("check formID").isEqualTo(actual.getFormID()))
            .satisfies(e -> assertThat(e.getFormType()).as("check formType").isEqualTo(actual.getFormType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSavedFormsUpdatableRelationshipsEquals(SavedForms expected, SavedForms actual) {
        assertThat(expected)
            .as("Verify SavedForms relationships")
            .satisfies(e -> assertThat(e.getChild()).as("check child").isEqualTo(actual.getChild()))
            .satisfies(e -> assertThat(e.getTemplateForm()).as("check templateForm").isEqualTo(actual.getTemplateForm()));
    }
}
