package mediformapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TemplateFormAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTemplateFormAllPropertiesEquals(TemplateForm expected, TemplateForm actual) {
        assertTemplateFormAutoGeneratedPropertiesEquals(expected, actual);
        assertTemplateFormAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTemplateFormAllUpdatablePropertiesEquals(TemplateForm expected, TemplateForm actual) {
        assertTemplateFormUpdatableFieldsEquals(expected, actual);
        assertTemplateFormUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTemplateFormAutoGeneratedPropertiesEquals(TemplateForm expected, TemplateForm actual) {
        assertThat(expected)
            .as("Verify TemplateForm auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTemplateFormUpdatableFieldsEquals(TemplateForm expected, TemplateForm actual) {
        assertThat(expected)
            .as("Verify TemplateForm relevant properties")
            .satisfies(e -> assertThat(e.getTemplateFormID()).as("check templateFormID").isEqualTo(actual.getTemplateFormID()))
            .satisfies(e -> assertThat(e.getFormType()).as("check formType").isEqualTo(actual.getFormType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTemplateFormUpdatableRelationshipsEquals(TemplateForm expected, TemplateForm actual) {}
}
